language: python

sudo: true

before_install:
  - if [[ $TOX_ENV == "frontend" ]]; then sudo apt-get update && sudo apt-get install nodejs npm; fi;

install:
  - pip install tox coveralls

# Explicit environments list here is a complete list of environments from tox.
# It is intentionally shortened.
env:
  - TOX_ENV=flake8
  - TOX_ENV=py34-django19-thumbs2x
  - TOX_ENV=py34-django18-thumbs2x
  - TOX_ENV=py34-django17-thumbs2x
  - TOX_ENV=py33-django18-thumbs2x
  - TOX_ENV=py33-django17-thumbs2x
  - TOX_ENV=py27-django19-thumbs2x
  - TOX_ENV=py27-django18-thumbs2x
  - TOX_ENV=py27-django17-thumbs2x
  - TOX_ENV=py34-django19-custom_image-thumbs2x
  - TOX_ENV=py34-django18-custom_image-thumbs2x
  - TOX_ENV=py34-django17-custom_image-thumbs2x
  - TOX_ENV=py34-django16-custom_image-thumbs2x
  - TOX_ENV=py33-django18-custom_image-thumbs2x
  - TOX_ENV=py33-django17-custom_image-thumbs2x
  - TOX_ENV=py33-django16-custom_image-thumbs2x
  - TOX_ENV=py27-django19-custom_image-thumbs2x
  - TOX_ENV=py27-django18-custom_image-thumbs2x
  - TOX_ENV=py27-django17-custom_image-thumbs2x
  - TOX_ENV=py27-django16-custom_image-thumbs2x
  - TOX_ENV=py34-django16-thumbs1x
  - TOX_ENV=py34-django15-thumbs1x
  - TOX_ENV=py33-django16-thumbs1x
  - TOX_ENV=py33-django15-thumbs1x
  - TOX_ENV=py27-django16-thumbs1x
  - TOX_ENV=py27-django15-thumbs1x
  - TOX_ENV=py26-django16-thumbs1x
  - TOX_ENV=py26-django15-thumbs1x
#  - TOX_ENV=py34-django_master-thumbs2x
#  - TOX_ENV=py33-django_master-thumbs2x
#  - TOX_ENV=py27-django_master-thumbs2x
  - TOX_ENV=frontend

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls --config_file=coverage.rc
  - mkdir -p shippable/codecoverage && cp coverage.xml shippable/codecoverage/coverage.xml

matrix:
  allow_failures:
    - env: TOX_ENV=py34-django_master-thumbs2x
    - env: TOX_ENV=py33-django_master-thumbs2x
    - env: TOX_ENV=py27-django_master-thumbs2x
